{ "count": 100,
  "espri1": "+ Kocanızla ortak özelliğiniz ne?\n- Aynı gün evlendik.",
  "espri2": "Kalbinin sesini dinle, güzelse kaset yap.",
  "espri3": "Annemin bahsettiği elalem diye bir örgüt var, illuminatiden daha tehlikeli yemin ederim.",
  "espri4": "+ Kanka seni çok özledim.\n- O yüzden mi yazmadın?\n+ Özlemin büyüsünü bozmak istemedim.",
  "espri5": "+ Hayallerini gerçekleştiriyor musun?\n- Hayır, onlar bana uğramıyor.",
  "espri6": "+ Akşam ne yaptın?\n- Kafama koyduklarımı düşündüm, hâlâ oradalar.",
  "espri7": "Dedem bana hayat öğüdü verdi: 'Oğlum, elini korkak alıştırma... ama elinde ne varsa tut.'",
  "espri8": "+ Neden sinemaya yalnız gittin?\n- Çünkü filmde yalnızlık işleniyordu.",
  "espri9": "+ Yeni hedefin ne?\n- Bugünden yarına sağ salim geçebilmek.",
  "espri10": "Sınavdan düşük aldım, öğretmen dedi ki: 'Kendini anlat.' Dedim: 'Kaç almışım, işte o kadarım.'",
  "espri11": "+ Yüzüme karşı neden dürüstsün?\n- Çünkü arkandan yalan söyleyecek kadar enerjim yok.",
  "espri12": "Telefonum 'akıllı' ama ben hâlâ bir numara çevirirken düşünüyorum.",
  "espri13": "+ Ders çalışıyor musun?\n- Evet, masanın başında kitapların gözüne bakıyorum, hâlâ anlamıyorlar.",
  "espri14": "Saatlerimi boşa harcamıyorum, sadece zamanı izliyorum.",
  "espri15": "+ Dostum çok şanslısın!\n- Evet, tüm şansımı kötü günde kullanmışım.",
  "espri16": "+ Hedefine ulaştın mı?\n- Hayır, hedefim de yolunu şaşırmış.",
  "espri17": "Babam, 'Sana güveniyorum' dedi. Düşündüm, keşke ben de kendime güvenebilsem.",
  "espri18": "+ Kilo mu aldın?\n- Hayır, dünya çekim gücünü artırmış.",
  "espri19": "Annemin dediğine göre evde çoraplar yaşıyor. Bir çift giriyor, bir tanesi dönüyor.",
  "espri20": "+ Ne zamandır diyettesin?\n- Tatlılara sadece bakmakla yetiniyorum, ama o da fazla tatlı geliyor.",
  "espri21": "+ Spor yapıyor musun?\n- Evet, her gün hayallerimin peşinden koşuyorum.",
  "espri22": "+ Kanka, hayat nasıl gidiyor?\n- Valla gidiyor ama nereye bilmiyorum.",
  "espri23": "Annem bana ‘Bir şeyi kırmadan önce düşün’ dedi. Düşündüm ve yine kırdım.",
  "espri24": "+ Hedeflerini küçük tutma.\n- Zaten benim hedeflerim, beni tutamıyor.",
  "espri25": "+ Bugün çok çalışkan hissediyorum.\n- Ne yaptın?\n+ Hissediyorum dedim, yaptım demedim.",
  "espri26": "+ Telefon neden susmuyor?\n- Çünkü susan telefon çok düşünceli olurdu.",
  "espri27": "+ Neden matematiği sevmiyorsun?\n- Sayılarla aramda bir hesaplaşma var.",
  "espri28": "+ Kanka, dertleşelim mi?\n- O zaman dertlerini sıraya koy, çünkü çok kalabalık.",
  "espri29": "Kedimle derin bir konuşma yaptım. Baktı, miyav dedi ve gitti. Sanırım o da beni anlamıyor.",
  "espri30": "+ Yemek yapmayı öğrendin mi?\n- Evet, aç kalmamayı öğrendim.",
  "espri31": "+ Bugün yeni insanlarla tanıştım.\n- Kimler?\n+ Banka çalışanları, fatura için çağırmışlar.",
  "espri32": "Hayatta hiçbir şeyden korkmam... elektrik faturasını görünceye kadar.",
  "espri33": "+ Kanka, başarı nedir?\n- Birinin ayağına top gelmeden, topu kaptırmamak.",
  "espri34": "+ Evde misin?\n- Evet ama zihnim çoktan dışarı çıkmış.",
  "espri35": "Sabah erken kalktım ama hâlâ uyuyorum, sadece gözlerim açık.",
  "espri36": "+ Tatil planın ne?\n- İki yastık, bir yorgan ve hayaller.",
  "espri37": "+ Kendine bir şey aldın mı?\n- Evet, biraz zaman. Ama hemen harcadım.",
  "espri38": "Üç dilek hakkım olsaydı, biri kesin hafta sonu pazartesiye dönmesin olurdu.",
  "espri39": "+ Bir başarı hikayesi duymak istiyorum.\n- Çamaşır makinem çalıştırdı ve yıkadı. İşte bu kadar.",
  "espri40": "+ Yeni bir şey keşfettim.\n- Ne keşfettin?\n+ Uyku. Tek problem, sürekli kayboluyor.",
  "espri41": "+ İki kitap aldım.\n- Okudun mu?\n+ Biri kalın geldi, diğerini de kalın diye okumadım.",
  "espri42": "Diyetisyene gittim, dedi ki: ‘Yediğinizi yazın.’ O günden beri roman yazıyorum.",
  "espri43": "+ Çay soğumuş.\n- Onu da üzmüşüz demek ki.",
  "espri44": "Trafikte sinirlenmeyin dediler. Sinirlenmedim, ama trafiğe sinir oldum.",
  "espri45": "+ Hayat zor mu?\n- Yok be, ben basitçe anlamıyorum sadece.",
  "espri46": "+ Hızlı yaşa, genç öl demişler.\n- Ben hızlı yedim, kilo aldım.",
  "espri47": "Yeni aldığım ayakkabıyı evde giydim. Şu an terlikle aynı işi görüyor.",
  "espri48": "+ Neden internette kayboldun?\n- Çünkü orada yön tabelası yok.",
  "espri49": "+ Motivasyonum yerlerde.\n- Yerden kaldır o zaman, üstüne basıp geçiyorsun.",
  "espri50": "Hayatım bir sinema filmi olsaydı, kesin fragmanda sıkılırdınız.",
  "espri51": "+ Kanka, hayat neden bu kadar zor?\n- Çünkü kolay olanı başkaları almış.",
  "espri52": "+ Bugün spor yaptım.\n- Ne yaptın?\n+ Spor salonunun önünden geçtim.",
  "espri53": "Geçmişi unutamıyorum, çünkü telefonumun hafızası dolu.",
  "espri54": "+ Kanka kilo mu aldın?\n- Yok, hava beni biraz şişirdi.",
  "espri55": "+ Ne iş yapıyorsun?\n- Boş işlerle meşgulüm.",
  "espri56": "+ Şu an ne düşünüyorsun?\n- Hiç. Zaten en sevdiğim şey bu.",
  "espri57": "+ Makarna yaptım.\n- Soslu mu?\n+ Hayır, üzgün.",
  "espri58": "Telefonumu şarja taktım, bir baktım 'yüzde 5' diyor. Dedim, sen bir 5 dakika düşün.",
  "espri59": "+ Çok kitap okuyorum.\n- Ne kitabı?\n+ Boş zaman kitabı. Çünkü boş zamanım çok.",
  "espri60": "+ Neden o kadar sessizsin?\n- Konuşmak için enerjim yok, dinliyorum sadece.",
  "espri61": "Dün spor salonuna yazıldım, ama içeri girmeden hemen ayrıldım. Salonun enerjisi bana yetti.",
  "espri62": "+ Yemek tariflerini takip ediyor musun?\n- Evet ama sonunda dışarıdan sipariş veriyorum.",
  "espri63": "Uyku benimle köşe kapmaca oynuyor. Ben yakalamaya çalışıyorum, o sürekli kaçıyor.",
  "espri64": "+ Kanka sana güvenebilir miyim?\n- Tabii, bende sırlar karışıyor, çözene aşk olsun.",
  "espri65": "+ Geç kaldın, neredeydin?\n- Zamanda kayboldum.",
  "espri66": "Aldığım kıyafetleri dolaba koydum. Şimdi hepsi bana trip atıyor, 'Bizi giy!' diye.",
  "espri67": "+ Hayatın anlamını buldun mu?\n- Bulduğumda sana link atarım.",
  "espri68": "+ Kanka bana destek ol.\n- Ne konuda?\n+ Ayakta duramıyorum, uyumam lazım.",
  "espri69": "+ Bugün çok çalışkan hissediyorum.\n- Kaç dakika çalıştın?\n+ Hissederek geçirdim, yeterli.",
  "espri70": "Biri ‘sessiz olun’ dediğinde, beynimdeki tüm sesler daha çok bağırmaya başlıyor.",
  "espri71": "+ Neden uyuyamıyorsun?\n- Düşüncelerim gece mesaisinde çalışıyor.",
  "espri72": "+ Evde kim var?\n- Ben ve hayallerim... Ama onlar biraz kırgın.",
  "espri73": "+ Yeni bir dil öğreniyorum.\n- Ne dili?\n+ Sessiz çığlıklar dili.",
  "espri74": "Bütçeme uygun bir şey buldum: Hava almak. O da bedava.",
  "espri75": "+ Hayat kısa dediler, ne yaptın?\n- Daha fazla uyudum.",
  "espri76": "+ Kanka hedeflerin var mı?\n- Var ama onlar da beni görmezden geliyor.",
  "espri77": "+ Sabah alarmı duymadım.\n- Neden?\n+ Alarm beni duymamış olabilir.",
  "espri78": "+ Çok çalıştım bugün.\n- Ne yaptın?\n+ Kahve makinesini çalıştırdım.",
  "espri79": "Hayallerimi büyütüyorum, çünkü gerçeğiyle başa çıkamıyorum.",
  "espri80": "+ Kilo veriyorum.\n- Kaç kilo gitti?\n+ Giden yok ama yolda olabilirler.",
  "espri81": "+ Sinemaya gittin mi?\n- Gittim ama filmi oturduğum koltuktan izledim.",
  "espri82": "Sakin olmamı söylediler, sakinliği arıyorum ama bir türlü bulamıyorum.",
  "espri83": "+ Beni anlamıyorsun.\n- Zaten çevirisi yok.",
  "espri84": "+ Spor salonu üyeliğin var mı?\n- Var ama üyelik kartı kadar spora gittim.",
  "espri85": "+ Kitap okuyor musun?\n- Evet, kitapçının vitrinini.",
  "espri86": "+ Neden sürekli gülüyorsun?\n- Çünkü ağlamak yoruyor.",
  "espri87": "Bugün koşuya çıktım. Koşacak motivasyon bulamayınca eve geri döndüm.",
  "espri88": "+ Kanka, hayat nasıl gidiyor?\n- Gittiği yere kadar, zaten ben takip edemiyorum.",
  "espri89": "Birisi ‘zaman her şeyin ilacıdır’ dedi. İlacın etki süresi biraz uzun sanırım.",
  "espri90": "+ Bugün yemek yapıyorum.\n- Neye göre?\n+ Aç olduğuma göre.",
  "espri91": "+ Telefonumun hafızası doldu.\n- Ne yaptın?\n+ Telefonla konuştum, sorunları çözemedik.",
  "espri92": "Uyumak istiyorum ama düşüncelerim: ‘Hayır, daha işimiz bitmedi!’",
  "espri93": "+ Saat kaç oldu?\n- Zaman durmuş gibi, boş ver.",
  "espri94": "Kendime bir şeyler aldım: Üç umut, iki hayal ve bir tane de boş çaba.",
  "espri95": "+ Hayattan ne öğrendin?\n- İyi bir öğretmen olmadığını.",
  "espri96": "Bugün kahve yaparken düşündüm: Bu kahve de benim gibi sıcak ama etkisiz.",
  "espri97": "+ Yarın erken kalkacağım.\n- Bugün nasıl gidiyor?\n+ Şimdiden yarın uyuyorum gibi.",
  "espri98": "Kilo vermek istedim ama bedenim, ‘Yok kanka, biz buradayız’ dedi.",
  "espri99": "+ Tatilde ne yaptın?\n- Sıkıldım, ama farklı bir yerde sıkıldım.",
  "espri100": "+ Bana bir tavsiye ver.\n- Yarın yap, çünkü bugün geç oldu."
}
